<a href="https://colab.research.google.com/github/bigdataguru/training-material/blob/master/TF_Cert_Hands_on_Jul2024.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
#checking the version of tf
import tensorflow as tf
print(tf.__version__)

2.15.0


In [5]:
#iimport numpy and check the version
import numpy as np
print(np.__version__)

1.25.2


In [6]:
#import everything from numpy
from numpy import *

In [10]:
#creating a tensor with constant values
a_constant = tf.constant([1,2,3,4,5])
print(a_constant)
a_constant

tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)


<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 3, 4, 5], dtype=int32)>

In [9]:
#create tensor variable
a_variable = tf.Variable([1,2,3,4,5,6])
print(a_variable)
a_variable

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>


<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [11]:
#creating a tf range
a_range=tf.range(start=1, limit = 10)
print(a_range)

tf.Tensor([1 2 3 4 5 6 7 8 9], shape=(9,), dtype=int32)
